### ISSUE TITLE
Feature Request: support date, time placeholders in Screencast filename setting

### ISSUE THREAD

**Issue by emystein** [henrywoo/kazam#13]
In the Filename prefix setting, I would like to be able to set current date and time in Filename prefix.

For example: setting **Kazam_screencast-{date}_{time}** would resolve to a file name **Kazam_screencast-2022-10-13_18_55**

![image](https://user-images.githubusercontent.com/947238/195717905-d900d41c-37c8-404e-b0f3-0a9fc2801982.png)

**Comment by henrywoo** [comment]
That is already supported by the latest version.
Please try the latest version:

`pip install kazam -U`

This should fix your issue.

![image](https://github.com/user-attachments/assets/eb85af5a-c45b-4537-b072-c5673629ec5a)
