### ISSUE TITLE
Is Wayland Supported?

### ISSUE THREAD

**Issue by lamyergeier** [henrywoo/kazam#14]
Is Wayland Supported?
OS: Ubuntu 22.04

**Comment by cccaballero** [comment]
I have installed tha last pip version in Ubuntu 22.04 and is not working with Wayland

**Comment by tissatussa** [comment]
i'm on Xubuntu 22.04 and Kazam is not working since a year or so ..

**Comment by henrywoo** [comment]
No. Wayland is not supported for now, only X11.
