### ISSUE TITLE
Cannot to capture desktop in Linux Mint 21.1

### ISSUE THREAD

**Issue by adityaharist** [henrywoo/kazam#17]
when I did capture from kazam. It wasn't save file to my home directory.
I tried stop then kazam doesn't respond.

**Comment by caioalbuka** [comment]
Estou com um problema parecido!
Não aparece a imagem da webcam, e não grava.
Quando grava aparece essa extensão de arquivo.
kazam_tkfnixk4.movie com 0 byte.

**Comment by henrywoo** [comment]
Please try the latest version:

`pip install -U kazam`

This should fix the issue.
