### ISSUE TITLE
Kazam screencast no longer working

### ISSUE THREAD

**Issue by tissatussa** [henrywoo/kazam#32]
Kazam had no problems until recently .. however, the screenshot function DOES still work .. i use the Kazam release according to Synaptic : v1.4.5 .. when i visit https://launchpad.net/~kazam-team/+archive/ubuntu/stable-series i see some PPA command but it doesn't work : no Release exists for my Jammy version (i'm on Xubuntu 22.04).

this happens when i execute Kazam by terminal :

```
$ kazam
WARNING Kazam - Failed to correctly detect operating system.
/usr/lib/python3/dist-packages/kazam/app.py:145: Warning: value "((GtkIconSize) 32)" of type 'GtkIconSize' is invalid or out of range for property 'icon-size' of type 'GtkIconSize'
  self.builder.add_from_file(os.path.join(prefs.datadir, "ui", "kazam.ui"))

(kazam:140335): Gtk-WARNING **: 17:19:39.259: Can't set a parent on widget which has a parent

(kazam:140335): Gtk-WARNING **: 17:19:39.273: Can't set a parent on widget which has a parent
```

the GUI did just quit here, but the process was still running (writing the output file bit by bit) so i only could do Ctrl-C to quit.

what's wrong ?
should i update my Kazam by compiling the latest source code of this GitHub repo ?

**Comment by Anshi10** [comment]
I am facing the same issue. Please provide a solution for this. I have tried to update the kazam. I have also tried to uninstall and again install kazam , problem still exist.

**Comment by faveoled** [comment]
Kazam from Ubuntu repos works for me on Ubuntu 22.04.3 Xorg

**Comment by henrywoo** [comment]
Please use code from this repo. Thanks.

**Comment by henrywoo** [comment]
This should have been resolved by the latest version. Please update with `pip install -U kazam`.
