### ISSUE TITLE
Doing an important screencasting at work, it did not ask me to save the file, and no .movie.mux file was generated, just the .movie file

### ISSUE THREAD

**Issue by massanen7** [henrywoo/kazam#34]
- I just had a really important screencast at work
- After about an hour of recording, I finished the recording, and Kazam didn't ask me to save the file
- There was a .movie file generated in videos folder (~280MB), but not a .movie.mux file
- I cannot regenerate the .movie file.

Is there a way to recover the recording with just the .movie file?

Thank you

**Comment by dawoodmalhi** [comment]
I also have encountered this problem. would be very helpful if someone can suggest a solution.

**Comment by henrywoo** [comment]
You need to set it in preference window.
