### ISSUE TITLE
Don't include colons in default file names

### ISSUE THREAD

**Issue by danboid** [henrywoo/kazam#40]
When you record a video with Kazam, by default it includes the time the capture started with the three sets of digits of the timestamp separated by colons.

FAT and exFAT (and NTFS?) cannot handle colons in file names so Kazam files have to be renamed before they can be copied onto most removable disks. I would prefer to see Kazam stop using colons in file names by default.

**Comment by henrywoo** [comment]
why colons in a file name?

**Comment by danboid** [comment]
This is an example default Kazam filename (with colons)

Screencast 2024-04-21 03:02:06.webm

FAT32, exfat will not handle this file name. Kazam should name it:

Screencast 2024-04-21 03-02-06.webm

or

Screencast_2024-04-21_03-02-06.webm

I prefer the second option with uderscores instead of spaces personally.

**Comment by henrywoo** [comment]
I think it is probably because you are not using code from this repo. With this repo, I got name like `genai_2024-04-20_18-43-52.webm`. Not sure which code base you are using?

**Comment by danboid** [comment]
How odd. I've installed the Debian trixie / testing package.

That seems like a very strange thing for them to change.

**Comment by henrywoo** [comment]
Please use code from this repo. The version is 1.5.7.

**Comment by danboid** [comment]
OK. Debian is still using 1.4.5

**Comment by henrywoo** [comment]
Please try the latest version:

`pip install kazam -U`

This should fix your issue.
