### ISSUE TITLE
Select Area should show what's being selected

### ISSUE THREAD

**Issue by IzStriker** [henrywoo/kazam#44]
I don't know  if this is a bug or just not a feature. When I select the specific area of my screen I want to record, it doesn't show what I'm actually selecting.
![image](https://github.com/henrywoo/kazam/assets/44909896/66d1bb84-3d5b-4f23-88ea-32d959ed864a)

This means I'm pretty much guessing what I'm selecting.

I'm running Garuda Linux which uses Plasma KDE.

**Comment by lukakostic** [comment]
Same except my whole screen is gray and not blurred (white text and selection box are visible). I do not have a compositor.

But other screenshot tools freeze my screen by screenshotting and then let me select, which is good solution for no compositor.

**Comment by henrywoo** [comment]
maybe you are using scale>1 or wayland.

Try the latest version of kazam and it has fix for scale>1 use case.
