### ISSUE TITLE
Error when trying to record

### ISSUE THREAD

**Issue by ValJed** [henrywoo/kazam#47]
Hello 👋🏼 

Just installed Kazam on Arch through the AUR: https://aur.archlinux.org/packages/kazam. Which is the version 1.4.5, not sure what the latest is.

I'm having this error when starting to record:
![image](https://github.com/henrywoo/kazam/assets/17548370/56644454-588b-42c5-9b4b-9c7b242cbaf3)

Not sure why it's happening, I have it installed on another machine that run on Arch too so it looks like a previous version worked.

I can help on this one if you want but I'm not familiar with python let me know.

Thank you or the great tool.

**Comment by henrywoo** [comment]
Please check out the source code from this repo and run kazam in the bin folder.

Let me know if there is any issue

**Comment by henrywoo** [comment]
This should have been resolved by the latest version. Please update with `pip install -U kazam`.
