### ISSUE TITLE
Area select = whole screen gray

### ISSUE THREAD

**Issue by lukakostic** [henrywoo/kazam#48]
![image](https://github.com/henrywoo/kazam/assets/41348897/a1604aca-2e90-48da-9459-644178c9fced)

Yeah i dont have a compositor.
Yet the builtin screenshot tool works - it takes a screenshot to freeze the screen and then lets me select.
So maybe do that when compositor not detected instead of just saying "expect the unexpected"
Hell, even not showing my selection box is better than graying out my screen but showing the box.

**Comment by henrywoo** [comment]
You should be able to use your mouse to draw a selection box, right?

**Comment by henrywoo** [comment]
This is probably because you are using wayland.
