### ISSUE TITLE
Kazam Recording start, push, and finished is not active when I run it on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by rakibulinux** [henrywoo/kazam#51]
Hi, @henrywoo, Installed Kazam using git version then I'm facing this issues. Kazam Recording start, push, and finished is not active when I run it on Ubuntu 24.04 LTS. Please take a look and let me know how I can fix it?

![image](https://github.com/henrywoo/kazam/assets/59226530/aee21315-e89c-4cf8-82c2-886921bf1ecf)

**Comment by maxlein** [comment]
Same for me

**Comment by henrywoo** [comment]
Use X11, not Wayland. Wayland doesn't work well with Nvidia driver. For now, kazam doesn't support wayland.
