### ISSUE TITLE
Crashes so much

### ISSUE THREAD

**Issue by caiot5** [henrywoo/kazam#52]
Been using Kazam for a while... 
Great idea but crashes too much.
When I say crashes I mean it can't Finish a recording (maybe when it gets big or something), then the only way is to kill Kazam (but losing the file for good).

**Comment by henrywoo** [comment]
Are you using this repo's version? Do you have any coredump or error message? You can run it in debug mode and see what happens when crashing.

**Comment by henrywoo** [comment]
This should have been resolved by the latest version. Please update with `pip install -U kazam`.
