### ISSUE TITLE
Kazam consumes CPU even when idle

### ISSUE THREAD

**Issue by cor3000** [henrywoo/kazam#53]
After stopping a recording the CPU usage of the kazam process remains active, and doesn't go down to ~0.

![image](https://github.com/henrywoo/kazam/assets/3894309/0040cba7-812d-4c15-b78c-e254830db5ec)

my linux version:

`Linux computer 6.9.0-1-MANJARO #1 SMP PREEMPT_DYNAMIC Mon May 13 07:01:28 UTC 2024 x86_64 GNU/Linux `

**Comment by henrywoo** [comment]
Try to update your kazam to latest version. 

![image](https://github.com/user-attachments/assets/0f5b2ea4-0f82-45fb-95c9-9960b3b7b586)

I got 0% CPU in my machine.

**Comment by cor3000** [comment]
thanks for trying to verify ... unfortunately I still can't install a newer version see #50 

I'll surely get back once I get the chance to run the newer version.
