### ISSUE TITLE
Cannot open preferences more than once

### ISSUE THREAD

**Issue by white-haired-uncle** [henrywoo/kazam#56]
Trying kazam for the first time.  Tried to save a quick video, and while I saw no error I wasn't prompted for a location so I didn't know where it was saved to (or if it was).  I looked in preferences.  I then found that I cannot return to the preferences menu unless I rm kazam.conf.

spartan$ uname -a
Linux spartan 5.15.0-116-generic #126-Ubuntu SMP Mon Jul 1 10:14:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

(I should mention I installed with 'sudo pip -U kazam' as I wanted kazam available to all users)

[typescript.txt](https://github.com/user-attachments/files/16481047/typescript.txt)

**Comment by henrywoo** [comment]
This should have been resolved by the latest version. Please update with `pip install -U kazam`.

**Comment by white-haired-uncle** [comment]
Confirm fixed for me.  Thank you.
