### ISSUE TITLE
Icon doesn't appear in ubuntu 22.04 search after installing using pip

### ISSUE THREAD

**Issue by lamualfa** [henrywoo/kazam#57]
>🔮 From GUI
>If you already have Kazam installed then Kazam icons will be displayed properly.

After running `pip install -U kazam`, I can't find the Kazam application in Ubuntu search. But the `kazam` cli command works well. Any suggestion about this?

**Comment by henrywoo** [comment]
You need to remove your previous kazam. and then run `pip install -U kazam`.
