### ISSUE TITLE
Fedora-40 and Gnome-46 fail to screenshot

### ISSUE THREAD

**Issue by jerome-diver** [henrywoo/kazam#64]
Application start, screenshot area start with a blackscreen and shot never show anything captured (no content at all). Running with Wayland standard installation of Fedora-40.

**Comment by henrywoo** [comment]
Wayland doesn't support Nvidia GPUs well, leading to performance and stability issues. As a result, Kazam doesn't support Wayland at this time. Please switch back to X11 to use Kazam following the guidelines below.

How to switch back from Wayland to X11?

Check: https://github.com/henrywoo/kazam/wiki#how-to-switch-back-from-wayland-to-x11
