### ISSUE TITLE
pip install -U kazam

### ISSUE THREAD

**Issue by MiguelSanzBr** [henrywoo/kazam#69]
File "/tmp/pip-install-khxjfk3e/py-itree_3a8d56ea96b5463d8e72e4bfbd0d568b/setup.py", line 63, in _check_build_environment
          raise RuntimeError(
      RuntimeError: CMake must be installed to build the following extensions: _itree
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for py-itree
  Running setup.py clean for py-itree
Successfully built dbus-python PyGObject
Failed to build py-itree
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (py-itree)

**Comment by vo2021** [comment]
try `pip install cmake`?

**Comment by MiguelSanzBr** [comment]
I tried and it worked thank you
